"""Add user info as the foreign key

Revision ID: 9dcb6e70990d
Revises: fcbc51fbb30a
Create Date: 2021-05-09 22:31:32.603354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dcb6e70990d'
down_revision = 'fcbc51fbb30a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('sqlite_sequence')
    op.add_column('todo', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'todo', 'users', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todo', type_='foreignkey')
    op.drop_column('todo', 'author_id')
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    # ### end Alembic commands ###
